<?php
return [
    'default' => 'pearledu',
    'themes' => [
        'pearledu' => [
            'label' => 'PearlEdu (VoxSign)',
            'tokens' => [
                'brand'        => '#053F5C',
                'brand-600'    => '#034A6B',
                'accent'       => '#F7AD19',
                'accent-soft'  => '#E8F7FA',
                'bg'           => '#F5FBFD',
                'surface'      => '#FFFFFF',
                'ink'          => '#053F5C',
                'muted'        => '#4A6270',
                'line'         => '#D4E8EE',
                'sidebar'      => '#053F5C',
                'sidebar-ink'  => '#9FE7F5',
                'radius'       => '14px',
                'font'         => "'Inter', system-ui, sans-serif",
            ],
        ],
        'moodle' => [
            'label' => 'Moodle (Boost)',
            'tokens' => [
                'brand'        => '#0F6CBF',
                'brand-600'    => '#0A5497',
                'accent'       => '#F98012',
                'accent-soft'  => '#FCE8D4',
                'bg'           => '#F2F2F2',
                'surface'      => '#FFFFFF',
                'ink'          => '#1D2125',
                'muted'        => '#6A737B',
                'line'         => '#DEE2E6',
                'sidebar'      => '#1D2125',
                'sidebar-ink'  => '#CED4DA',
                'radius'       => '8px',
                'font'         => "'Open Sans', system-ui, sans-serif",
            ],
        ],
        'emis' => [
            'label' => 'EMIS (Government)',
            'tokens' => [
                'brand'        => '#0B4DA2',
                'brand-600'    => '#083C7E',
                'accent'       => '#F2B705',
                'accent-soft'  => '#FBEEC2',
                'bg'           => '#EEF2F7',
                'surface'      => '#FFFFFF',
                'ink'          => '#10243E',
                'muted'        => '#5B6B80',
                'line'         => '#D5DEE9',
                'sidebar'      => '#0B4DA2',
                'sidebar-ink'  => '#C9DAF0',
                'radius'       => '6px',
                'font'         => "'Roboto', system-ui, sans-serif",
            ],
        ],
    ],
];
